-- Crear Base de datos
CREATE DATABASE DB_SAME

-- Crear nuestra tabla de empresa

USE DB_SAME
GO

CREATE TABLE [dbo].[TB_EMPRESA3](
	[ID_EMPRESA] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE_EMPRESA] [varchar](50) NULL,
	[DIRECCION] [varchar](500) NULL,
	[TELEFONO] [varchar](20) NULL,
	[ESTADO] [bit] NULL,
	[FECHA_CREACION] [datetime] NULL,
)
GO

--LISTAR
SELECT * FROM TB_EMPRESA

--INSERTAR
INSERT INTO TB_EMPRESA 
			(NOMBRE_EMPRESA,DIRECCION_EMPRESA,TELEFONO_EMPRESA) 
	   VALUES 
			('SAME','GUATEMALA','50212345678')


--UPDATE
UPDATE TB_EMPRESA SET
		NOMBRE_EMPRESA = 'AMATE'
		WHERE 
			ID_EMPRESA = 4
		
UPDATE TB_EMPRESA SET
	DIRECCION_EMPRESA ='GUATEMALA',
	TELEFONO_EMPRESA = '50212345678'
		


--ELIMINAR 
DELETE TB_EMPRESA WHERE ID_EMPRESA = 5

UPDATE TB_EMPRESA SET ESTADO = 0 WHERE ID_EMPRESA = 6

--LISTAR
SELECT * FROM TB_EMPRESA WHERE ESTADO = 1
